services:
  rethinkdb:
    image: rethinkdb:2.4
    container_name: stf-rethinkdb
    network_mode: host
    volumes:
      - rethinkdb-data:/data
    restart: unless-stopped

  stf:
    image: devicefarmer/stf:latest
    container_name: stf
    depends_on:
      - rethinkdb
    network_mode: host
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - RETHINKDB_PORT_28015_TCP=tcp://127.0.0.1:28015
    command: >
      stf local
      --public-ip ${PUBLIC_IP}
      --adb-host 127.0.0.1
      --adb-port 5037
      --allow-remote
    restart: unless-stopped

  stf-exporter:
    image: node:18
    container_name: stf-exporter
    working_dir: /app
    volumes:
      - ./exporter:/app
    command: sh -c "npm install && node stf-exporter.js"
    depends_on:
      - rethinkdb
    network_mode: host
    ports:
      - "9105:9105"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  rethinkdb-data: